In [7]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[0,0,1]])
b = np.sort(a.view('i8,i8,i8'), order=['f1'], axis=0).view(np.int)
print(b)

[[0 0 1]
 [1 2 3]
 [4 5 6]]


In [8]:
import numpy as np

# let numpy guess the type with dtype=None
infile = [[720 549 896 549 896 582 720 582 0]                                    
 [688  72 944  72 944 100 688 100   0]
 [240  70 368  70 368 102 240 102   0]
 [ 32 456 128 456 128 482  32 482   0]
 [176 455 320 455 320 481 176 481   0]
 [400 456 480 456 480 481 400 481   0]
 [240  32 848  32 848  69 240  69   0]
 [ 32 360 256 360 256 383  32 383   0]
 [ 32 231 320 231 320 261  32 261   0]
 [768 470 880 470 880 564 768 564   0]
 [ 32 265 144 265 144 288  32 288   0]
 [ 32 421 336 421 336 446  32 446   0]
 [ 32 201 624 201 624 228  32 228   0]
 [ 32 328 512 328 512 351  32 351   0]
 [720 514 768 514 768 553 720 553   0]
 [ 32 163 464 163 464 193  32 193   0]
 [ 32 296 336 296 336 320  32 320   0]
 [ 16 540 192 540 192 567  16 567   0]
 [672 501 720 501 720 569 672 569   0]
 [ 16 391 192 391 192 416  16 416   0]]
my_data = np.genfromtxt(infile, dtype=None, names=["a", "b", "c", "d","e","f","g","h","i"])

# access columns by name
print(my_data["b"]) # column 1

# sort column 1 and column 0 
my_data.sort(order=["b"])

print(my_data)

SyntaxError: invalid syntax (<ipython-input-8-c9b85a1c821d>, line 4)